### PR TITLE
Project board fixes

### PR DESCRIPTION
**Pull request by maggie0002**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Various fixes from the project board. 

**Which issue (if any) does this pull request address?**

Closes: https://github.com/maggie0002/balena-device-ui/issues/79
Closes: https://github.com/maggie0002/balena-device-ui/issues/69

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by maggie0002** [comment]
@nucleardreamer I have run out of days this week to finish this off but will pick it up again next week. A lot of ticks in the box already though. 

If you want you can start looking over the changes to far and I will continue next week in a new PR.

**Comment by maggie0002** [comment]
@nucleardreamer this should do it for now. Looking to merge this now. Not sure how to go about the review, maybe just have a scan over for anything obviously problematic, or anything that doesn't build or display properly. Will do a proper bug discovery the dog food way.

**Comment by maggie0002** [comment]
> I now have time to review this, so I figure I will run it on a couple devices and make sure there isn't anything outstanding? @maggie0002

I think that make sense. After this PR the next one will make things easier, because the next one will build all the apps too and will be available as assets in the PR. 

For now, there is the normal interface as usual, and if you go to `yourhostname.local/app` you will find the PWA version to play around with too.

**Comment by nucleardreamer** [comment]
Alright! I didn't run into any visible problems myself with this whole PR. I think its fine to roll without linking the PWA for now like you mentioned. This is fantastic!!

**Review by nucleardreamer — APPROVED** [review]

**Pull request merged**
