### PR TITLE
Add ability to develop directly on a Balena device with hot reload

### PR DESCRIPTION
**Pull request by maggie0002**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
- Added ability to develop directly on a Balena device with hot reload
- Migrated Quasar to Vite instead of Webpack, as Webpack was too resource demanding for hot reload on a Raspberry Pi 4.

Here is a head start:

1. Rename docker-compose-dev.yml to docker-compose.yml (annoyingly Balena CLI doesn't allow specifying a docker-compose file)
2. Push the build to your device.
3. Check the console for the device after the NFS container starts. You may need to run a modprobe on the host of the device, but the messages from the container will prompt you accordingly.
4. Mount the folder on your local system. (If using a Mac, something like: `mount_nfs balena.local:/nfs /directory/where/you/want/it/locally`
5. Open the UI from the device (visit `balena.local`)
6. Open the new mounted folder on the Mac in visual studio code. Edit a file and watch the hot reload magic happening in the browser. Game changer for developing components that rely on WiFi, Supervisor, Balena SDK, peripherals like sensors etc. etc. 7. 

Considered doing it the other way, having the Mac as the server and the Balena device as the client, but Mac uses virtual docker env and didn't like acting as a server. Moreover, users could have other operating systems (windows) and versions that would require more support and more problems. Using Balena device as the server keeps a common context to work from, and a Linux context which is easier to use with NFS. 

Caveats, of course it will not be as fluid as developing locally, but will save tons of time when developing components specific to the hardware. First load of the page from the device, and first save in Visual Studio will take a bit longer, but thanks to selective caching of static components in the node_modules, after the first loads it flows pretty nicely. Tested on a Raspberry Pi 4.

:beer:

### CODE REVIEW

**Review by nucleardreamer — APPROVED** [review]
This is a game changer for developing in a quick way. It might be a good idea to document the process for getting this setup in the `README`, and also adding a note that this will not work if you are in `local mode` while developing on a balena device, that got me hung up for a minute when trying it out

**Comment by maggie0002** [comment]
> This is a game changer for developing in a quick way. It might be a good idea to document the process for getting this setup in the `README`, and also adding a note that this will not work if you are in `local mode` while developing on a balena device, that got me hung up for a minute when trying it out

What happens if you are in local more?

Had to resolve some merge conflicts that voided the review approval, will have to submit it again.

**Comment by nucleardreamer** [comment]
Nice, I see what you mean. Local mode gets rid of the release running on the device, and let's you `balena push <IP>` that gives live reload whenever you save changes, but it's doing it just through rebuilding the image layer deltas, so it still takes a while to develop with, this is much more rapid

**Review by nucleardreamer — APPROVED** [review]

**Comment by maggie0002** [comment]
> Nice, I see what you mean. Local mode gets rid of the release running on the device, and let's you `balena push <IP>` that gives live reload whenever you save changes, but it's doing it just through rebuilding the image layer deltas, so it still takes a while to develop with, this is much more rapid

Ah yeah I see. 

Come to think of it, local mode probably doesn't work anyway? Would it try to reach the Balena Cloud to get device info that doesn't exist? Maybe it needs to default to offline device info mode when in local?

**Comment by nucleardreamer** [comment]
> > Nice, I see what you mean. Local mode gets rid of the release running on the device, and let's you `balena push <IP>` that gives live reload whenever you save changes, but it's doing it just through rebuilding the image layer deltas, so it still takes a while to develop with, this is much more rapid
> 
> Ah yeah I see.
> 
> Come to think of it, local mode probably doesn't work anyway? Would it try to reach the Balena Cloud to get device info that doesn't exist? Maybe it needs to default to offline device info mode when in local?

Ah yes it does work, it simply replaces the release coming down from the supervisor with your own build (and builds the containers on device as well), but every time you change a CSS file, it rebuilds the whole front end so ends up taking a long time. The API calls still pulls from the cloud, so there is no idea of being offline

**Comment by maggie0002** [comment]
> > > Nice, I see what you mean. Local mode gets rid of the release running on the device, and let's you `balena push <IP>` that gives live reload whenever you save changes, but it's doing it just through rebuilding the image layer deltas, so it still takes a while to develop with, this is much more rapid
> > 
> > 
> > Ah yeah I see.
> > Come to think of it, local mode probably doesn't work anyway? Would it try to reach the Balena Cloud to get device info that doesn't exist? Maybe it needs to default to offline device info mode when in local?
> 
> Ah yes it does work, it simply replaces the release coming down from the supervisor with your own build (and builds the containers on device as well), but every time you change a CSS file, it rebuilds the whole front end so ends up taking a long time. The API calls still pulls from the cloud, so there is no idea of being offline

Yeah, I gave up on the local mode builds with local push and yarn installs some time back. At least on the RPI's, with SD cards, it was just painfully slow and sometimes the device would fall over completely. Probably could have saved myself a whole bunch of time with some investment in some better hardware to develop on, but ah well.

**Pull request merged**
