### PR TITLE
Allow setting of hostname

### PR DESCRIPTION
**Pull request by maggie0002**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Allows setting of hostname of the device

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**
I encountered an error which I haven't been able to reproduce. The documentation (https://www.balena.io/docs/reference/supervisor/supervisor-api/#get-v1devicehost-config) says that the endpoint being used reads configuration from things previously set with PATCH. I am wondering if the Patch request hasn't already been called, whether the GET endpoint works. I can't test this scenario because it would require reinstalling a device and I only have remote hardware.

@mrpher or @nucleardreamer could you test this for me? It would require flashing a card with a new Balena OS on a fleet, then having it join the fleet and see if there are any errors on first boot in the Balena Cloud log. It should simply say:

```
warn: Changing hostname to balena
warn: Hostname changed.
```

Anything more and we have an issue.

### CODE REVIEW

**Comment by mrpher** [comment]
@maggie0002  I didn't see any errors.  Flashed a fresh OS on existing fleet and everything seems fine....  Logs are from first boot.

```
 mdns-advertise  
 mdns-advertise  > mdns-advertise@0.0.1 start
 mdns-advertise  > node build/index.js
 mdns-advertise  
 py-wifi-connect  [2022-03-14 15:59:48] - [INFO] - Checking for previously configured Wi-Fi connections...
 balena-device-ui  Listening on port 80
 mdns-advertise  * mdns - starting
 mdns-advertise  * mdns - IP: 192.168.68.111
 mdns-advertise  * mdns - adding balena.local at address 192.168.68.111 to local MDNS pool
 mdns-advertise  * mdns - avahi group: /Client0/EntryGroup1
 py-wifi-connect  [2022-03-14 15:59:58] - [INFO] - A Wi-Fi connection or hotspot is already active.
 py-wifi-connect  [2022-03-14 15:59:58] - [INFO] - Ready...
 py-wifi-connect  [2022-03-14 15:59:58] - [INFO] - Listening on 172.17.0.1 port 9090
```

Visiting http://balena.local works out of the box too. 
I didn't customize the hostname though.  I'm not sure where that config is done honestly.

**Comment by maggie0002** [comment]
> @maggie0002 I didn't see any errors. Flashed a fresh OS on existing fleet and everything seems fine.... Logs are from first boot.
> 
> ```
>  mdns-advertise  
>  mdns-advertise  > mdns-advertise@0.0.1 start
>  mdns-advertise  > node build/index.js
>  mdns-advertise  
>  py-wifi-connect  [2022-03-14 15:59:48] - [INFO] - Checking for previously configured Wi-Fi connections...
>  balena-device-ui  Listening on port 80
>  mdns-advertise  * mdns - starting
>  mdns-advertise  * mdns - IP: 192.168.68.111
>  mdns-advertise  * mdns - adding balena.local at address 192.168.68.111 to local MDNS pool
>  mdns-advertise  * mdns - avahi group: /Client0/EntryGroup1
>  py-wifi-connect  [2022-03-14 15:59:58] - [INFO] - A Wi-Fi connection or hotspot is already active.
>  py-wifi-connect  [2022-03-14 15:59:58] - [INFO] - Ready...
>  py-wifi-connect  [2022-03-14 15:59:58] - [INFO] - Listening on 172.17.0.1 port 9090
> ```
> 
> Visiting http://balena.local works out of the box too. I didn't customize the hostname though. I'm not sure where that config is done honestly.

I think you may have pushed the wrong branch. That looks like the main branch with MDNS doing the work. Could you try with this 'set-hostname' branch? 

`git clone https://github.com/maggie0002/balena-device-ui.git -b Set-hostname` and then push that to the fleet before connecting a new device.

**Comment by mrpher** [comment]
Think I reproduced your error... From my logs.

```
 balena-device-ui  Listening on port 80
 balena-device-ui  2022-03-14 16:30:46:3046 warn: Changing hostname to balena.
 balena-device-ui  2022-03-14 16:30:46:3046 warn: Hostname changed.
```

**Comment by mrpher** [comment]
My mistake. Here are the complete logs.  And yes, http://balena.local works. 

```
 balena-device-ui  Listening on port 80
 balena-device-ui  2022-03-14 16:30:46:3046 warn: Changing hostname to balena.
 balena-device-ui  2022-03-14 16:30:46:3046 warn: Hostname changed.
 balena-device-ui  Listening on port 80
 balena-device-ui  Error fetching current hostname.
Killing service 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
Supervisor starting
 balena-device-ui  Listening on port 80
 balena-device-ui  2022-03-14 16:30:46:3046 warn: Changing hostname to balena.
 balena-device-ui  2022-03-14 16:30:46:3046 warn: Hostname changed.
 balena-device-ui  Listening on port 80
 balena-device-ui  Error fetching current hostname.
Killing service 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
Service is already stopped, removing container 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
Killed service 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
Installing service 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
Installed service 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
Starting service 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
Started service 'py-wifi-connect sha256:16531a30c7d0a466428c526cfabd7a04404ff341925bc144bf88e8145e919c7b'
 py-wifi-connect  [2022-03-14 16:31:48] - [INFO] - Checking for previously configured Wi-Fi connections...
 py-wifi-connect  [2022-03-14 16:31:58] - [INFO] - A Wi-Fi connection or hotspot is already active.
 py-wifi-connect  [2022-03-14 16:31:58] - [INFO] - Ready...
 py-wifi-connect  [2022-03-14 16:31:58] - [INFO] - Listening on 172.17.0.1 port 9090
```

**Comment by mrpher** [comment]
I removed the SET_HOSTNAME variable, pushed to the fleet, and re-flashed the device.  Came online, behaved normally, but _without_ http://balena.local working.

```
 py-wifi-connect  [2022-03-14 19:13:30] - [INFO] - Checking for previously configured Wi-Fi connections...
 balena-device-ui  Listening on port 80
 py-wifi-connect  [2022-03-14 19:13:40] - [INFO] - A Wi-Fi connection or hotspot is already active.
 py-wifi-connect  [2022-03-14 19:13:40] - [INFO] - Ready...
 py-wifi-connect  [2022-03-14 19:13:40] - [INFO] - Listening on 172.17.0.1 port 9090
Supervisor starting
 py-wifi-connect  [2022-03-14 19:24:25] - [INFO] - Checking for previously configured Wi-Fi connections...
 py-wifi-connect  [2022-03-14 19:24:35] - [INFO] - A Wi-Fi connection or hotspot is already active.
 py-wifi-connect  [2022-03-14 19:24:35] - [INFO] - Ready...
 py-wifi-connect  [2022-03-14 19:24:35] - [INFO] - Listening on 172.17.0.1 port 9090
 balena-device-ui  Listening on port 80
```

**Comment by maggie0002** [comment]
> I'll try modifying the dockerfile to install curl and try again

You can add it with `api add curl` in the container, rather than rebuilding it.

**Comment by nucleardreamer** [comment]
One other thing we will want to test for is: if avahi will pickup the hostname change and still advertise without a reboot. So basically start with the hostname set, change the variable, see if the `variable.local` is still accessible or if the previous variable persists. 

If that is the behavior - we can simply add a note in the UI saying something like "Please reboot the machine to make the new hostname accessible"

**Comment by mrpher** [comment]
@nucleardreamer I may have missed this in other convos, but why wouldn't we just take the balena device name at init (ie, frosty-pine) and allow http://frosty-pine.local?  Now that I'm thinking about it, is it really necessary to allow the hostname to be changed for users?  I doubt many would actually change it.  As long as its unique and not trying to name every device balena.  In which case I'm not even sure how it would handle collisions with multiple devices trying to resolve to http://balena.local

**Comment by nucleardreamer** [comment]
@mrpher oh yes, there is a little bit of context behind this. There are a ton of use cases relating to [open fleets](https://hub.balena.io/) where the user doesn't have access to the balena dashboard at all, hence the strong use case for this project. Not only will they not know their device name by default, but essentially they would have to go look up the IP in their router or nmap to find the device. 

The ideal use case is something like the the [ribbit network](https://github.com/Ribbit-Network/ribbit-network-frog-sensor), where they are seeking a local UI, and would probably but something like `http://ribbit.local` as their address in their deployment. I think just setting `balena.local` can be our default, but expecting most users to change it.

**Comment by mrpher** [comment]
@nucleardreamer Got it, makes perfect sense now.  I guess also it could come in very hand for openbalena users too who lack the device url option, but want an easy way to get to the right device.

**Comment by maggie0002** [comment]
@mrpher this should be working now. Could you update from this branch and then push to a fleet, then have a newly flashed device join the fleet just like before? We are hoping for:

```
15.03.22 10:45:02 (+0000)  balena-device-ui  2022-03-15 10:45:02:452 warn: Changing hostname to balena.
15.03.22 10:45:02 (+0000)  balena-device-ui  2022-03-15 10:45:02:452 warn: Hostname changed.
```

Would be good if you could share the whole console output, just to be sure. 

And then would also be good to hear how the experience is, is the device available right away from balena.local or did you have to restart it?

**Comment by nucleardreamer** [comment]
I have yet to be able to test this, but will give it a whirl soon!

**Comment by nucleardreamer** [comment]
Alright, after testing:
- Setting hostname on first boot does work.
- Setting hostname _after_ first boot, does require a restart for the new `hostname.local` to resolve, so either we have to put a note under the input field in configuration, or figure out a way to restart the avahi service on the hostos
- After setting the hostname, there is no way I can see to get back to what you had configured in environment variables previously? I'm not sure if that is a concern.
- On the same note - we might want to fill in the default input value for hostname to what it's currently set to, there is no other place in the UI to know what it's set to.

**Comment by maggie0002** [comment]
> Alright, after testing:
> 
> * Setting hostname on first boot does work.
> * Setting hostname _after_ first boot, does require a restart for the new `hostname.local` to resolve, so either we have to put a note under the input field in configuration (saying "hey, please reboot to have this take effect for .local resolution"), or figure out a way to restart the avahi service on the hostos.
> * After setting the hostname, there is no way I can see to get back to what you had configured in environment variables previously? I'm not sure if that is a concern.
> * On the same note - we might want to fill in the default input value for hostname to what it's currently set to, there is no other place in the UI to know what it's set to.

Some good food for thought. I am surprised you had to reboot it. When I used to use this endpoint on a Raspberry Pi or Orange pi it would come back up again. Sometimes it took a little while, but always reappeared. No harm if having a message to prompt people that a restart may be required though. I think that would be better than triggering a restart automatically, I try and avoid automating things that restart devices. Just because potential bugs can be breaking if something goes wrong.

I had gone back and forth on the idea of restoring back to the env variable as default. I considered something that would allow that to be triggered, but it seemed a fairly unusual scenario and meant more endpoints. If someone really needed too, they could always delete the lock file, or just set the hostname to the same value as the env var. 

Setting the input field with the current value would probably be best done with an API call to the supervisor to get the hostname. It has already felt a little sluggish at times with all the calls, I think it's probably better to keep it minimal? Presumably the user will already know the current hostname, as they have had to type it in their browser. We could fetch the hostname from the url in the browser, but then if a user under some odd circumstance used the IP to access it it would look very confusing.

**Comment by nucleardreamer** [comment]
So I tested this again just now, after a little while it _did_ come up with the new hostname set (after 60 seconds or so). I deleted the device, re-imaged and tried again, it was stuck on the old hostname still and I gave up after 20 minutes of waiting. This could be due to caching in my local network as well, but even if it is, it's probably a scenario someone would run into regardless. 

I will say that this is working as expected for the most part. Worst case is we can revisit if we have a 100% repro of this issue (which I can't get it to do now it seems like). Lets move ahead!

**Review by nucleardreamer — APPROVED** [review]

**Pull request merged**
